---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 13

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: pip
    run_list:
      - recipe[test::pip]
    verifier:
      inspec_tests:
        - test/smoke/pip
    attributes:
  - name: source
    run_list:
      - recipe[test::source]
    verifier:
      inspec_tests:
        - test/smoke/source
    attributes:
  - name: package
    run_list:
      - recipe[test::package]
    verifier:
      inspec_tests:
        - test/smoke/package
    attributes:
